Personal Expense Tracker
Problem Statement:

In today’s fast-paced world, individuals need to track and manage their expenses effectively. Your task is to build a personal expense tracker that allows users to log daily expenses, categorize them, and track spending against a monthly budget. The tracker should also be able to save and load expenses from a file for future reference.

Objectives:
1.    Design and implement a personal expense tracker that enables users to manage their expenses
2.    Allow users to categorize expenses and set monthly budgets
3.    Implement file-handling functionality to save and load expense data
4.    Create an interactive, menu-driven interface for ease of use

Steps to Perform:

1.  Add an expense:
•  Create a function to prompt the user for expense details. Ensure you ask for:

The date of the expense in the format YYYY-MM-DD
The category of the expense, such as Food or Travel
The amount spent
A brief description of the expense
•  Store the expense in a list as a dictionary, where each dictionary includes the date, category, amount, and description as key-value pairs
Example:
{'date': '2024-09-18', 'category': 'Food', 'amount': 15.50, 'description': 'Lunch with friends'}



2.  View expenses:
•   Write a function to retrieve and display all stored expenses
      Ensure the function loops through the list of expenses and displays the date, category, amount, and description for each entry
•   Validate the data before displaying it
      If any required details (date, category, amount, or description) are missing, skip the entry or notify the user that it’s incomplete


3.  Set and track the budget:
•   Create a function that allows the user to input a monthly budget. Prompt the user to:
     Enter the total amount they want to budget for the month
•   Create another function that calculates the total expenses recorded so far
     Compare the total with the user’s monthly budget
     If the total expenses exceed the budget, display a warning (Example: You have exceeded your budget!)
     If the expenses are within the budget, display the remaining balance (Example: You have 150 left for the month)



4.  Save and load expenses:
•   Implement a function to save all expenses to a CSV file, with each row containing the date, category, amount, and description of each expense
•   Create another function to load expenses from the CSV file. When the program starts, it should:
     Read the saved data from the file
     Load it back into the list of expenses so the user can see their previous expenses and continue from where they left off



5.  Create an interactive menu:

Build a function to display a menu with the following options:
Add expense
View expenses
Track budget
Save expenses
Exit
Allow the user to enter a number to choose an option
•   Implement the following conditions:
     If the user selects option 1, call the function to add an expense
     If the user selects option 2, call the function to view expenses
     If the user selects option 3, call the function to track the budget
     If the user selects option 4, call the function to save expenses to the file
     If the user selects option 5, save the expenses and exit the program

In [5]:
#Requirement #1 - Add an Expense

import pandas as pd
from datetime import datetime


all_expenses = [] #Creates a variable called all_expenses

def add_expenses(): #creating my function

    while True:  #This is going to create my loop that will keep going until the user input's no

        while True:
            exp_date_input = input('Enter the date of the expense (MM-DD-YYYY): ').strip() #Removing the blank spaces before/after
            if not exp_date_input:
                print("Date cannot be blank. Please enter the date.")
                continue
            try:
                datetime.strptime(exp_date_input, '%m-%d-%Y') #Validating the date input
                exp_date = exp_date_input # Store the validated string
                break
            except ValueError:#if it isn't in the right format, it will ask the user to input again.
                print("Invalid date format. Please use MM-DD-YYYY (e.g., 12-15-2023).")

        while True:
            exp_type = input('Enter the type of expense: ').strip() #Same as above, just with the expense type
            if not exp_type:
                print("Expense type cannot be blank. Please enter the type of expense.")
                continue
            break

        while True:
            exp_amt_str = input(f'Enter the amount of the expense: $').strip() #same as above, just with the expense amount.
            if not exp_amt_str:
                print("Amount cannot be blank. Please enter the amount.")
                continue
            try:
                exp_amt = float(exp_amt_str)
                if exp_amt < 0: # Optional: add check for non-negative amount
                    print("Amount cannot be negative. Please enter a valid amount.")
                    continue
                break
            except ValueError:
                print("Invalid amount. Please enter a numerical value (e.g., 185.64).")

        all_expenses.append({'date': exp_date, 'type': exp_type, 'amount': exp_amt}) #the apend will ensure that I add to the list

        another_exp = input('Add another expense? (yes/no): ')
        if another_exp.lower() == 'no': #if the user inputs no - the program moves on the displaying results
            break
add_expenses()  #Calling my function
print("Thank you for entering your expenses")
expenses_df = pd.DataFrame(all_expenses) #using pandas for better output view
expenses_df['date'] = pd.to_datetime(expenses_df['date']) #In my research, it looks like converting to a panda date/time will allow me to better analyze data

styled_df = expenses_df.style.format({
    'date': lambda x: x.strftime('%m-%d-%Y'),
    'amount': "{:.2f}"
}).set_table_styles([
    {'selector': 'th',
     'props': [('background-color', 'lightblue'),
               ('color', 'darkblue'),
               ('font-weight', 'bold')]}
])
display(styled_df)

Enter the date of the expense (MM-DD-YYYY): 01-01-2026
Enter the type of expense: meal
Enter the amount of the expense: $1040.03
Add another expense? (yes/no): no
Thank you for entering your expenses

In [6]:
# Requirement #2 - Set/Track Budgets

monthly_budget = 0.0 # Creating a monthly budget

def set_budget():
    global monthly_budget
    while True:
        budget_input = input('Enter your monthly budget amount: $').strip()
        if not budget_input:
            print("Budget amount cannot be blank. Please enter a value.")
            continue
        try:
            monthly_budget = float(budget_input)
            if monthly_budget < 0:
                print("Budget cannot be negative. Please enter a positive amount.")
                continue
            print(f"Monthly budget set to ${monthly_budget:.2f}")
            break
        except ValueError:
            print("Invalid amount. Please enter a numerical value for the budget.")

def track_budget():  #this function will tell the user how much of their budget is left after looking through expenses entered
    if monthly_budget == 0.0:
        print("Please set your monthly budget first.")
        return

    total_expenses = sum(expense['amount'] for expense in all_expenses)

    print(f"Total expenses recorded: ${total_expenses:.2f}")
    print(f"Monthly budget: ${monthly_budget:.2f}")

    if total_expenses > monthly_budget:
        print(f"Warning: You have exceeded your budget by ${total_expenses - monthly_budget:.2f}!")
    else:
        remaining_balance = monthly_budget - total_expenses
        print(f"You have ${remaining_balance:.2f} left for the month.")

set_budget()
track_budget()

Enter your monthly budget amount: $1500
Monthly budget set to $1500.00
Total expenses recorded: $1040.03
Monthly budget: $1500.00
You have $459.97 left for the month.

In [7]:
# Requirement #3 - Save and Load Expenses

def save_expenses(filename='expenses.csv'):
    if not all_expenses:
        print("No expenses to save.")
        return
    expenses_df = pd.DataFrame(all_expenses)
    expenses_df.to_csv(filename, index=False)
    print(f"Expenses saved to {filename}")

def load_expenses(filename='expenses.csv'):
    global all_expenses
    try:
        loaded_df = pd.read_csv(filename)
        # Convert DataFrame back to list of dictionaries
        all_expenses = loaded_df.to_dict(orient='records')
        print(f"Expenses loaded from {filename}")
        # Re-format the date if needed, depending on how it was saved
        for expense in all_expenses:
            if 'date' in expense and isinstance(expense['date'], str):
                # Assuming the saved date format is YYYY-MM-DD (pandas default for to_csv)
                try:
                    expense['date'] = datetime.strptime(expense['date'], '%Y-%m-%d').strftime('%m-%d-%Y')
                except ValueError:
                    # If it's already MM-DD-YYYY or another format, handle or ignore
                    pass

    except FileNotFoundError:
        print(f"No expense file found at {filename}. Starting with an empty expense list.")
        all_expenses = []
    except Exception as e:
        print(f"Error loading expenses: {e}")
        all_expenses = []

print("Saving current expenses...") #this step is to save / load expenses and demonstrate the function. The file will be saved as expense.csv
save_expenses()

print("Clearing current expenses for demonstration...")
all_expenses = []

print("Loading expenses from file...")
load_expenses()

print("Loaded expenses:")
if all_expenses:
    loaded_expenses_df = pd.DataFrame(all_expenses)
    styled_loaded_df = loaded_expenses_df.style.format({
        'date': lambda x: x.strftime('%m-%d-%Y') if isinstance(x, pd.Timestamp) else x,
        'amount': "{:.2f}"
    }).set_table_styles([
        {'selector': 'th',
         'props': [('background-color', 'lightblue'),
                   ('color', 'darkblue'),
                   ('font-weight', 'bold')]}
    ])
    display(styled_loaded_df)
else:
    print("No expenses loaded.")

Saving current expenses...
Expenses saved to expenses.csv
Clearing current expenses for demonstration...
Loading expenses from file...
Expenses loaded from expenses.csv
Loaded expenses:

In [8]:
def view_expenses():
    if not all_expenses:
        print("No expenses to display.")
        return

    # Convert list of dictionaries to DataFrame for better display
    expenses_df = pd.DataFrame(all_expenses)
    expenses_df['date'] = expenses_df['date'].apply(lambda x:
                                                     pd.to_datetime(x, errors='coerce') if isinstance(x, str)
                                                     else x)
    expenses_df = expenses_df.dropna(subset=['date']) # Drop rows where date conversion failed

    print("\n--- Your Expenses ---")
    styled_df = expenses_df.style.format({
        'date': lambda x: x.strftime('%m-%d-%Y') if isinstance(x, pd.Timestamp) else x,
        'amount': "{:.2f}"
    }).set_table_styles([
        {'selector': 'th',
         'props': [('background-color', 'lightblue'),
                   ('color', 'darkblue'),
                   ('font-weight', 'bold')]}
    ])
    display(styled_df)
    print("---------------------")

In [9]:
def main_menu():
    global all_expenses # Ensure we can modify the global list of expenses

    # Load expenses when the program starts
    load_expenses()

    while True:
        print("\n--- Expense Tracker Menu ---")
        print("1. Add an expense")
        print("2. View expenses")
        print("3. Set budget")
        print("4. Track budget")
        print("5. Save expenses")
        print("6. Exit")
        print("--------------------------")

        choice = input("Enter your choice (1-6): ").strip()

        if choice == '1':
            add_expenses()
        elif choice == '2':
            view_expenses()
        elif choice == '3':
            set_budget()
        elif choice == '4':
            track_budget()
        elif choice == '5':
            save_expenses()
        elif choice == '6':
            print("Saving expenses before exiting...")
            save_expenses()
            print("Exiting Expense Tracker. Goodbye!")
            break
        else:
            print("Invalid choice. Please enter a number between 1 and 6.")

In [ ]:
#This is calling the main menu function which is operating as a simple menu.

main_menu()

Expenses loaded from expenses.csv

--- Expense Tracker Menu ---
1. Add an expense
2. View expenses
3. Set budget
4. Track budget
5. Save expenses
6. Exit
--------------------------
Enter your choice (1-6): 1
Enter the date of the expense (MM-DD-YYYY): 05-15-2026
Enter the type of expense: car
Enter the amount of the expense: $105
Add another expense? (yes/no): no

--- Expense Tracker Menu ---
1. Add an expense
2. View expenses
3. Set budget
4. Track budget
5. Save expenses
6. Exit
--------------------------
Enter your choice (1-6): 2

--- Your Expenses ---

---------------------

--- Expense Tracker Menu ---
1. Add an expense
2. View expenses
3. Set budget
4. Track budget
5. Save expenses
6. Exit
--------------------------
Enter your choice (1-6): 5
Expenses saved to expenses.csv

--- Expense Tracker Menu ---
1. Add an expense
2. View expenses
3. Set budget
4. Track budget
5. Save expenses
6. Exit
--------------------------